### ISSUE TITLE
Euler Cylinder Test Case fails in Debug Mode

### ISSUE THREAD

**Issue by abtin98** [dougshidong/PHiLiP#27]
output:

49: An error occurred in line <1715> of file </home/abtinameri/share/dealii/source/fe/mapping_fe_field.cc> in function
49:     dealii::CellSimilarity::Similarity dealii::MappingFEField<dim, spacedim, VectorType, DoFHandlerType>::fill_fe_values(const typename dealii::Triangulation<dim, spacedim>::cell_iterator&, dealii::CellSimilarity::Similarity, const dealii::Quadrature<dim>&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, dealii::internal::FEValuesImplementation::MappingRelatedData<dim, spacedim>&) const [with int dim = 2; int spacedim = 2; VectorType = dealii::LinearAlgebra::distributed::Vector<double>; DoFHandlerType = dealii::DoFHandler<2, 2>; typename dealii::Triangulation<dim, spacedim>::cell_iterator = dealii::TriaIterator<dealii::CellAccessor<2, 2> >; typename dealii::Mapping<dim, spacedim>::InternalDataBase = dealii::Mapping<2, 2>::InternalDataBase]
49: The violated condition was: 
49:     det > 1e-12 * Utilities::fixed_power<dim>( cell->diameter() / std::sqrt(double(dim)))
49: Additional information: 
49:     The image of the mapping applied to cell with center [0.542651 1.31008] is distorted. The cell geometry or the mapping are invalid, giving a non-positive volume fraction of -0.116411 in quadrature point 83.
49: 
49: Stacktrace:
49: -----------
49: #0  /home/abtinameri/share/dealii/install/lib/libdeal_II.g.so.9.2.0-pre: dealii::MappingFEField<2, 2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::DoFHandler<2, 2> >::fill_fe_values(dealii::TriaIterator<dealii::CellAccessor<2, 2> > const&, dealii::CellSimilarity::Similarity, dealii::Quadrature<2> const&, dealii::Mapping<2, 2>::InternalDataBase const&, dealii::internal::FEValuesImplementation::MappingRelatedData<2, 2>&) const
49: #1  /home/abtinameri/share/dealii/install/lib/libdeal_II.g.so.9.2.0-pre: dealii::FEValues<2, 2>::do_reinit()
49: #2  /home/abtinameri/share/dealii/install/lib/libdeal_II.g.so.9.2.0-pre: void dealii::FEValues<2, 2>::reinit<dealii::hp::DoFHandler, false>(dealii::TriaIterator<dealii::DoFCellAccessor<dealii::hp::DoFHandler<2, 2>, false> > const&)
49: #3  /home/abtinameri/Desktop/thesis/PHiLiP/build/bin/PHiLiP_2D: PHiLiP::Tests::EulerCylinder<2, 4>::run_test() const
49: #4  /home/abtinameri/Desktop/thesis/PHiLiP/build/bin/PHiLiP_2D: main
49: --------------------------------------------------------
49: 
49: Calling MPI_Abort now.
49: To break execution in a GDB session, execute 'break MPI_Abort' before running. You can also put the following into your ~/.gdbinit:
49:   set breakpoint pending on
49:   break MPI_Abort
49:   set breakpoint pending auto
49: [abtinameri-ThinkPad-T460:06505] 1 more process has sent help message help-mpi-api.txt / mpi-abort
49: [abtinameri-ThinkPad-T460:06505] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
1/1 Test #49: MPI_2D_EULER_INTEGRATION_CYLINDER_LONG ...***Failed  500.26 sec

**Comment by dougshidong** [comment]
Error occurs with the p3 solution (p4 HighOrderGrid), on the 2nd grid level with 127 cells.

Cell 57 is causing the issue with a negative metric Jacobian field near a corner. 

Attached is a screenshot demonstrating the mapping from reference to physical space of the quadrature nodes. We would visually not have guessed that the Jacobians are negative since the node locations do not suggest any crossover.

The contour plot shows the metric Jacobian field, especially the negative corner region.

![Screenshot from 2019-10-12 12-28-34](https://user-images.githubusercontent.com/9758507/66704641-d82fed00-eceb-11e9-9eae-02559afbfdbc.png)

To be further investigated. Relevant papers below.


@Article{Toulorge2016,
  author    = {Thomas Toulorge and Jonathan Lambrechts and Jean-Fran{\c{c}}ois Remacle},
  title     = {Optimizing the geometrical accuracy of curvilinear meshes},
  journal   = {Journal of Computational Physics},
  year      = {2016},
  volume    = {310},
  pages     = {361--380},
  month     = {apr},
  doi       = {10.1016/j.jcp.2016.01.023},
  file      = {:Toulorge2016 - Optimizing the geometrical accuracy of curvilinear meshes.pdf:PDF},
  publisher = {Elsevier {BV}},
}

@InCollection{Geuzaine2015,
  author    = {C. Geuzaine and A. Johnen and J. Lambrechts and J. -F. Remacle and T. Toulorge},
  title     = {The Generation of Valid Curvilinear Meshes},
  booktitle = {Notes on Numerical Fluid Mechanics and Multidisciplinary Design},
  publisher = {Springer International Publishing},
  year      = {2015},
  pages     = {15--39},
  doi       = {10.1007/978-3-319-12886-3_2},
  file      = {:Geuzaine2015 - The Generation of Valid Curvilinear Meshes.pdf:PDF},
}

@PhdThesis{Engvall2018,
  author      = {Engvall, Luke H.},
  title       = {Geometrically Exact and Analysis Suitable Mesh Generation using Rational Bernstein-Bezier Elements},
  institution = {University of Colorado},
  year        = {2018},
  language    = {English},
  note        = {Copyright - Database copyright ProQuest LLC; ProQuest does not claim copyright in the individual underlying works; Last updated - 2018-07-24},
  isbn        = {9780355966350},
  pages       = {168},
  url         = {https://proxy.library.mcgill.ca/login?url=https://search.proquest.com/docview/2059766758?accountid=12339},
  abstract    = {This dissertation presents two novel contributions to the fields of isogeometric analysis and p-version finite elements. First, we present a framework for geometrically exact volumetric mesh generation. By leveraging ideas from both traditional mesh generation as well as isogeometric analysis, we develop a framework for volumetric mesh generation using rational Bernstein--Bezier discretizations. Within this framework, we provide a set of easily verifiable sufficient conditions for guaranteeing that a mesh will be geometrically exact. Second, we develop a complete theory of mesh quality for these rational Bernstein--B\'{e}zier elements. From this, we derive a set of easily computable mesh quality metrics for verifying that a rational Bernstein--Bezier discretization will be analysis suitable.},
  file        = {:Engvall2018 - Geometrically Exact and Analysis Suitable Mesh Generation Using Rational Bernstein Bezier Elements.pdf:},
  journal     = {ProQuest Dissertations and Theses},
  keywords    = {Applied sciences; Curvilinear mesh generation; Higher-order finite elements; Isogeometric analysis; Mesh generation; Engineering; 0537:Engineering},
  timestamp   = {2018-11-14},
}

**Comment by dougshidong** [comment]
Just uploading my MATLAB scripts used to plot before I discard them.

[plot_jacobians.zip](https://github.com/dougshidong/PHiLiP/files/3722050/plot_jacobians.zip)

**Comment by dougshidong** [comment]
Even more visualisation. Attached the grid can be opened in Paraview version 4.5 and above (for high order element visualisation).
[Mesh-2D_GridP04-0001.0000.zip](https://github.com/dougshidong/PHiLiP/files/3723454/Mesh-2D_GridP04-0001.0000.zip)

The image shows a cell of the cylinder and a bunch of evenly spaced reference point mapped onto the physical domain by expanding 
![CodeCogsEqn](https://user-images.githubusercontent.com/9758507/66736218-952e6080-ee36-11e9-974c-96f72f2f93a1.gif)

Very interestingly, you can see the line of points starting to fold onto itself.

![Screenshot from 2019-10-14 03-48-02](https://user-images.githubusercontent.com/9758507/66735916-c2c6da00-ee35-11e9-9288-b9b6cf55cb1b.png)

![Screenshot from 2019-10-14 03-48-17](https://user-images.githubusercontent.com/9758507/66735915-c2c6da00-ee35-11e9-93d9-29510a5e8e5c.png)

Still investigating.

**Comment by dougshidong** [comment]
Fixed by suing MappingQGeneric instead of MappingQ to generate the curved inner mesh.
